In [1]:
# pip install pingouin
import numpy as np
import pandas as pd

# create data
df = pd.DataFrame({'technique': np.repeat(['Self-study', 'Video lessons', 'Classroom'], 5),
                   'current_grade': [67, 88, 75, 77, 85,
                                     92, 69, 77, 74, 78, 
                                     96, 91, 88, 82, 80],
                   'exam_score': [77, 79, 72, 74, 69,
                                  78, 88, 83, 84, 90,
                                  85, 89, 83, 88, 95]})

# view data 
df

        technique  current_grade  exam_score
0      Self-study             67          77
1      Self-study             88          79
2      Self-study             75          72
3      Self-study             77          74
4      Self-study             85          69
5   Video lessons             92          78
6   Video lessons             69          88
7   Video lessons             77          83
8   Video lessons             74          84
9   Video lessons             78          90
10      Classroom             96          85
11      Classroom             91          89
12      Classroom             88          83
13      Classroom             82          88
14      Classroom             80          95

In [2]:
# pip install pingouin
from pingouin import ancova

# perform ANCOVA
ancova(data=df, dv='exam_score', covar='current_grade', between='technique')

# p-unc = p-value uncorrected, our p-value
# in most cases, p-values under 0.05 indicate statistical significance
# in this case, if np2 goes up, p-unc probably down

# np2 => effect% of the column towards the target (current grade)
# the other's are measuring the same thing or just variables used by the ancova equation

          Source          SS  DF          F     p_unc       np2
0      technique  573.310323   2  17.950936  0.000344  0.765468
1  current_grade   58.343041   1   3.653561  0.082341  0.249329
2       Residual  175.656959  11        NaN       NaN       NaN