<b>chi-test: see if the columns are dependent </b>

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency
 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.DataFrame({'Season' : ['Winter', 'Winter', 'Winter', 'Summer', 'Summer'] * 10,
                   'AvgTemp' : ['Cold', 'Cold', 'Warm', 'Warm', 'Warm'] * 10
                  })
df

    Season AvgTemp
0   Winter    Cold
1   Winter    Cold
2   Winter    Warm
3   Summer    Warm
4   Summer    Warm
5   Winter    Cold
6   Winter    Cold
7   Winter    Warm
8   Summer    Warm
9   Summer    Warm
10  Winter    Cold
11  Winter    Cold
12  Winter    Warm
13  Summer    Warm
14  Summer    Warm
15  Winter    Cold
16  Winter    Cold
17  Winter    Warm
18  Summer    Warm
19  Summer    Warm
20  Winter    Cold
21  Winter    Cold
22  Winter    Warm
23  Summer    Warm
24  Summer    Warm
25  Winter    Cold
26  Winter    Cold
27  Winter    Warm
28  Summer    Warm
29  Summer    Warm
30  Winter    Cold
31  Winter    Cold
32  Winter    Warm
33  Summer    Warm
34  Summer    Warm
35  Winter    Cold
36  Winter    Cold
37  Winter    Warm
38  Summer    Warm
39  Summer    Warm
40  Winter    Cold
41  Winter    Cold
42  Winter    Warm
43  Summer    Warm
44  Summer    Warm
45  Winter    Cold
46  Winter    Cold
47  Winter    Warm
48  Summer    Warm
49  Summer    Warm

In [3]:
# calculate a contingency table to see how the sums
# distribute between the combinations of the values
contigency = pd.crosstab(df['Season'], df['AvgTemp'])
contigency

AvgTemp  Cold  Warm
Season
Summer      0    20
Winter     20    10

In [4]:
# convert the contingencyies into percentage
contigency_pct = pd.crosstab(df['Season'], df['AvgTemp'], normalize='index')
contigency_pct

AvgTemp      Cold      Warm
Season
Summer   0.000000  1.000000
Winter   0.666667  0.333333

In [5]:
# Chi-square test of independence.
# value close to 0 implies the two groups are dependent on each other
c, p, dof, expected = chi2_contingency(contigency)
f"{p:.15f}"

'0.000009896734625'